---
  AWSTemplateFormatVersion: "2010-09-09"
  Description: "Creates a VPC"
  Parameters:
    VPCName:
      Description: The name of the VPC being created.
      Type: String
      Default: "Very cool vpc"
  Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.10.10.0/24
